//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA.Core.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPA.Core.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   UI Object に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category1 {
            get {
                return ResourceManager.GetString("Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Credential option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category10 {
            get {
                return ResourceManager.GetString("Category10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category2 {
            get {
                return ResourceManager.GetString("Category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category3 {
            get {
                return ResourceManager.GetString("Category3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category4 {
            get {
                return ResourceManager.GetString("Category4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fixed format option に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category5 {
            get {
                return ResourceManager.GetString("Category5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formatting options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category6 {
            get {
                return ResourceManager.GetString("Category6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Start column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category7 {
            get {
                return ResourceManager.GetString("Category7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   End column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category8 {
            get {
                return ResourceManager.GetString("Category8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category9 {
            get {
                return ResourceManager.GetString("Category9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonText {
            get {
                return ResourceManager.GetString("CommonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies that the remaining activities will continue even if the current activity fails. Only Boolean values are supported. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the current working directory.  This field only accepts string variables.  Note: All string variables must be placed between quotes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description10 {
            get {
                return ResourceManager.GetString("Description10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text extracted from the file stored in the string variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description100 {
            get {
                return ResourceManager.GetString("Description100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the file to be written. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description101 {
            get {
                return ResourceManager.GetString("Description101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text to be written to the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description102 {
            get {
                return ResourceManager.GetString("Description102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the credential obtained in the system に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description103 {
            get {
                return ResourceManager.GetString("Description103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the amount of time, in milliseconds, to wait for an activity to run before an error is raised.  The default is 30000 milliseconds (30 seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description104 {
            get {
                return ResourceManager.GetString("Description104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The secure password of the retrieved credentials に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description105 {
            get {
                return ResourceManager.GetString("Description105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   User name of the retrieved voucher に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description106 {
            get {
                return ResourceManager.GetString("Description106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the amount of time, in milliseconds, to wait for an activity to run before an error is raised. The default value is 30000 milliseconds (30 seconds) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description107 {
            get {
                return ResourceManager.GetString("Description107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies whether automation should continue even if the activity raises an error に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description108 {
            get {
                return ResourceManager.GetString("Description108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the username of the credential に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description109 {
            get {
                return ResourceManager.GetString("Description109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can find the full path to the executabel file of the application you want to open.  Note: All strings must be placed between quotes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description11 {
            get {
                return ResourceManager.GetString("Description11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Set the password for the credential に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description110 {
            get {
                return ResourceManager.GetString("Description110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the credential to update に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description111 {
            get {
                return ResourceManager.GetString("Description111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The PowerShell command to execute. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description112 {
            get {
                return ResourceManager.GetString("Description112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A collection of PSObjects passed to the writer of the pipeline used to execute the command.  Can be the output of another InvokePowerShell activity. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description113 {
            get {
                return ResourceManager.GetString("Description113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A set of type parameters objets returned when the command is executed.  Can be used to pipe several InvokePowerShell activities. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description114 {
            get {
                return ResourceManager.GetString("Description114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Workflow file path, must be enclosed in double quotes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description115 {
            get {
                return ResourceManager.GetString("Description115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The data retrieved from the clipboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description12 {
            get {
                return ResourceManager.GetString("Description12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text to be copied to the clipboard. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description13 {
            get {
                return ResourceManager.GetString("Description13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Copy files or folders に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description14 {
            get {
                return ResourceManager.GetString("Description14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataColumn object to be attached to the column set of the DataTable.  If this property is set, all properties under the Options category are ignored に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description15 {
            get {
                return ResourceManager.GetString("Description15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the new column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description16 {
            get {
                return ResourceManager.GetString("Description16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataTable object to add the column to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description17 {
            get {
                return ResourceManager.GetString("Description17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify whether the fields in the new column are allowed to be empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description18 {
            get {
                return ResourceManager.GetString("Description18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies whether the value of the column is automatically incremented when a new row is added に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description19 {
            get {
                return ResourceManager.GetString("Description19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Process name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the value in each row of the new column must be unique に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description20 {
            get {
                return ResourceManager.GetString("Description20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the maximum length of the value of the new column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description21 {
            get {
                return ResourceManager.GetString("Description21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataRow object to be added to the DataTable. If this property is set, the ArrayRow property is ignored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description22 {
            get {
                return ResourceManager.GetString("Description22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An array of objects to add to the DataTable.  The type of each object should be mapped to the type of its corresponding column in the DataTable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description23 {
            get {
                return ResourceManager.GetString("Description23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataTable object to add row data to に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description24 {
            get {
                return ResourceManager.GetString("Description24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a DataTable generated from row and column information に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description25 {
            get {
                return ResourceManager.GetString("Description25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataTable object to clear all data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description26 {
            get {
                return ResourceManager.GetString("Description26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataTable variable to filter.  This field only supports DataTable variables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description27 {
            get {
                return ResourceManager.GetString("Description27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies whether to filter the table by keeping or deleting the target row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description28 {
            get {
                return ResourceManager.GetString("Description28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify whether to filter the table by retaining or deleting the target column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description29 {
            get {
                return ResourceManager.GetString("Description29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The Text property used to find specific UI elements when performing activities に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3 {
            get {
                return ResourceManager.GetString("Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter the result DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description30 {
            get {
                return ResourceManager.GetString("Description30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   a single-row operation of the DataTable variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description31 {
            get {
                return ResourceManager.GetString("Description31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the source of unstructured data to be converted to a table.  This field only supports String variables. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description32 {
            get {
                return ResourceManager.GetString("Description32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If you use OCR for fetching and the Get Word Information check box is selected, this field contains IEnumerable&lt;KeyValuePair&lt;Rectangle,String&gt;&gt; variables with WordsInfo values に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description33 {
            get {
                return ResourceManager.GetString("Description33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the size of the column to be created in the table.  This field only supports the IEnumerable &lt;Int32&gt; variable. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description34 {
            get {
                return ResourceManager.GetString("Description34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the character to use as the column separator.  This field only supports String variables. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description35 {
            get {
                return ResourceManager.GetString("Description35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the character to be used as a newline separator.  This field only supports String variables. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description36 {
            get {
                return ResourceManager.GetString("Description36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   When selected, the column or row type is automatically detected, whether it is String, Int32, etc. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description37 {
            get {
                return ResourceManager.GetString("Description37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If checked, the first identified column is used as the column header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description38 {
            get {
                return ResourceManager.GetString("Description38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   If checked, the first identified row is used as the row header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description39 {
            get {
                return ResourceManager.GetString("Description39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A collection of process objects representing the processes that are running in the current Windows session. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4 {
            get {
                return ResourceManager.GetString("Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generated DataTable variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description40 {
            get {
                return ResourceManager.GetString("Description40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataRow object from which to retrieve the value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description41 {
            get {
                return ResourceManager.GetString("Description41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataColumn object whose value is to be retrieved from the DataRow.  If this property is set, the ColumnName and ColumnIndex properties are ignored. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description42 {
            get {
                return ResourceManager.GetString("Description42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The index of the column whose value is to be retrieved from the DataRow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description43 {
            get {
                return ResourceManager.GetString("Description43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the column whose value is to be retrieved from the DataRow.  If this property is set, the ColumnIndex property is ignored に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description44 {
            get {
                return ResourceManager.GetString("Description44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify the column value of the DataRow に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description45 {
            get {
                return ResourceManager.GetString("Description45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The first table to use in this operation is stored in the DataTable variable.  This field only supports DataTable variables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description46 {
            get {
                return ResourceManager.GetString("Description46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The second table to be used in this operation is stored in the DataTable variable.  This field only supports DataTable variables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description47 {
            get {
                return ResourceManager.GetString("Description47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataTable variable in which to perform the lookup に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description48 {
            get {
                return ResourceManager.GetString("Description48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value to search for in the specified DataTable variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description49 {
            get {
                return ResourceManager.GetString("Description49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A process type object that describes the process to be closed. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description5 {
            get {
                return ResourceManager.GetString("Description5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataColumn object whose value is to be retrieved from the DataRow.  Setting a variable in this property field disables the other two properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description50 {
            get {
                return ResourceManager.GetString("Description50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The index of the column whose value is to be retrieved from the DataRow.  Setting a variable in this property field disables the other two properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description51 {
            get {
                return ResourceManager.GetString("Description51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the column whose value is to be retrieved from the DataRow.  Setting a variable in this property field disables the other two properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description52 {
            get {
                return ResourceManager.GetString("Description52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns the cell found at the coordinates between this column and the value in the RowIndex property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description53 {
            get {
                return ResourceManager.GetString("Description53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns the column index of the cell found at the coordinates between this column and the value of the RowIndex property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description54 {
            get {
                return ResourceManager.GetString("Description54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Returns the column name of the cell found at the coordinates between this column and the value in the RowIndex property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description55 {
            get {
                return ResourceManager.GetString("Description55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value found in the cell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description56 {
            get {
                return ResourceManager.GetString("Description56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row index of the cell に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description57 {
            get {
                return ResourceManager.GetString("Description57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge the DataTable object of the source DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description58 {
            get {
                return ResourceManager.GetString("Description58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataTable object to be added to the target DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description59 {
            get {
                return ResourceManager.GetString("Description59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the process to close. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description6 {
            get {
                return ResourceManager.GetString("Description6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specify what to do when merging two DataTables に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description60 {
            get {
                return ResourceManager.GetString("Description60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataTable object to write to the string に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description61 {
            get {
                return ResourceManager.GetString("Description61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable as a string output に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description62 {
            get {
                return ResourceManager.GetString("Description62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataTable object from which to remove the column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description63 {
            get {
                return ResourceManager.GetString("Description63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataColumn object to be removed from the column set of the DataTable.  If this property is set, the other two column index options are ignored に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description64 {
            get {
                return ResourceManager.GetString("Description64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The index of the column to remove from the column set of the DataTable.  If this property is set, the other two column index options are ignored に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description65 {
            get {
                return ResourceManager.GetString("Description65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the column to remove from the column set of the DataTable.  If this property is set, the other two column index options are ignored に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description66 {
            get {
                return ResourceManager.GetString("Description66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataRow object to delete.  Ignore row indexing option if this property is set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description67 {
            get {
                return ResourceManager.GetString("Description67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The index of the row to delete.  Ignore DataRow indexing option if this property is set に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description68 {
            get {
                return ResourceManager.GetString("Description68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataTable variable from which to remove duplicate rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description69 {
            get {
                return ResourceManager.GetString("Description69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Specifies the amount of time, in milliseconds, to wait for an activity to run before throwing an error.  The default is 3000 milliseconds (3 seconds). に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description7 {
            get {
                return ResourceManager.GetString("Description7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Outputs a DataTable with duplicate rows removed, stored in the DataTable variable.  Placing the same variable as the variable in the Input field changes the initial variable, while providing a new variable makes the initial variable unaffected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description70 {
            get {
                return ResourceManager.GetString("Description70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The DataTable variable to be sorted に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description71 {
            get {
                return ResourceManager.GetString("Description71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The variable of the column sorted by it.  This field only supports DataColumn variables.  Setting a variable in this property field disables the other two properties に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description72 {
            get {
                return ResourceManager.GetString("Description72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The sorted DataTable variable.  Placing the same variable as the variable in the Input field changes the initial variable, and adding a new variable leaves the initial variable unaffected. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description73 {
            get {
                return ResourceManager.GetString("Description73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter UIElement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description74 {
            get {
                return ResourceManager.GetString("Description74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text of the popup window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description75 {
            get {
                return ResourceManager.GetString("Description75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The title of the popup window. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description76 {
            get {
                return ResourceManager.GetString("Description76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Duration until the pop-up window closes automatically.  By default, pop-ups do not close. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description77 {
            get {
                return ResourceManager.GetString("Description77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   This represents the full path or external URL of the HTML file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description78 {
            get {
                return ResourceManager.GetString("Description78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The string returned by the provided HTML page. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description79 {
            get {
                return ResourceManager.GetString("Description79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Parameters that can be passed to the application at startup. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description8 {
            get {
                return ResourceManager.GetString("Description8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The label of the form field. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description80 {
            get {
                return ResourceManager.GetString("Description80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   An array of options to choose from.  If you set it to contain only one element, a text box will appear to compose the text.  If it is set to contain 2 or 3 elements, they will appear as the radio button to choose from.  If it is set to contain more than 3 items, they will be displayed as a combo box for selection.  This field only supports string array variables. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description81 {
            get {
                return ResourceManager.GetString("Description81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter the title of the dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description82 {
            get {
                return ResourceManager.GetString("Description82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The value inserted by the user in the input dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description83 {
            get {
                return ResourceManager.GetString("Description83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The title of the message box dialog. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description84 {
            get {
                return ResourceManager.GetString("Description84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text to display in the message box. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description85 {
            get {
                return ResourceManager.GetString("Description85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   A string representing the button pressed in the message box dialog.  It can be: Ok, Yes, No or Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description86 {
            get {
                return ResourceManager.GetString("Description86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the file.  If the path is incomplete, create a file in the project folder. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description87 {
            get {
                return ResourceManager.GetString("Description87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The text to be attached to the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description88 {
            get {
                return ResourceManager.GetString("Description88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the file to be copied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description89 {
            get {
                return ResourceManager.GetString("Description89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   You can find the full file path of the executable for the application you want to open.  Note: All strings must be placed between quotes. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description9 {
            get {
                return ResourceManager.GetString("Description9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The target path of the file to be copied. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description90 {
            get {
                return ResourceManager.GetString("Description90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The full path to the directory to be created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description91 {
            get {
                return ResourceManager.GetString("Description91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The name of the file to create. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description92 {
            get {
                return ResourceManager.GetString("Description92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The full path to the file to be created. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description93 {
            get {
                return ResourceManager.GetString("Description93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the file or directory to be permanently deleted. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description94 {
            get {
                return ResourceManager.GetString("Description94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the file to move. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description95 {
            get {
                return ResourceManager.GetString("Description95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The target path to move the file. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description96 {
            get {
                return ResourceManager.GetString("Description96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The full path to check. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description97 {
            get {
                return ResourceManager.GetString("Description97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Declare whether a document or file is found. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description98 {
            get {
                return ResourceManager.GetString("Description98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The path to the file to be read. に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description99 {
            get {
                return ResourceManager.GetString("Description99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Window selector に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName1 {
            get {
                return ResourceManager.GetString("DisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   position に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName10 {
            get {
                return ResourceManager.GetString("DisplayName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column width に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName11 {
            get {
                return ResourceManager.GetString("DisplayName11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column separator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName12 {
            get {
                return ResourceManager.GetString("DisplayName12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line separator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName13 {
            get {
                return ResourceManager.GetString("DisplayName13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV parsing に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName14 {
            get {
                return ResourceManager.GetString("DisplayName14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Type automatic detection に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName15 {
            get {
                return ResourceManager.GetString("DisplayName15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column heading に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName16 {
            get {
                return ResourceManager.GetString("DisplayName16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row header に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName17 {
            get {
                return ResourceManager.GetString("DisplayName17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName18 {
            get {
                return ResourceManager.GetString("DisplayName18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName19 {
            get {
                return ResourceManager.GetString("DisplayName19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allowed to be empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName2 {
            get {
                return ResourceManager.GetString("DisplayName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName20 {
            get {
                return ResourceManager.GetString("DisplayName20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName21 {
            get {
                return ResourceManager.GetString("DisplayName21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName22 {
            get {
                return ResourceManager.GetString("DisplayName22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName23 {
            get {
                return ResourceManager.GetString("DisplayName23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName24 {
            get {
                return ResourceManager.GetString("DisplayName24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JoinType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName25 {
            get {
                return ResourceManager.GetString("DisplayName25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Find value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName26 {
            get {
                return ResourceManager.GetString("DisplayName26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cell value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName27 {
            get {
                return ResourceManager.GetString("DisplayName27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Row index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName28 {
            get {
                return ResourceManager.GetString("DisplayName28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   aims に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName29 {
            get {
                return ResourceManager.GetString("DisplayName29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto increment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName3 {
            get {
                return ResourceManager.GetString("DisplayName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   source に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName30 {
            get {
                return ResourceManager.GetString("DisplayName30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Merge operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName31 {
            get {
                return ResourceManager.GetString("DisplayName31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName32 {
            get {
                return ResourceManager.GetString("DisplayName32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName33 {
            get {
                return ResourceManager.GetString("DisplayName33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sort に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName34 {
            get {
                return ResourceManager.GetString("DisplayName34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Date time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName35 {
            get {
                return ResourceManager.GetString("DisplayName35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Conversion type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName36 {
            get {
                return ResourceManager.GetString("DisplayName36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName37 {
            get {
                return ResourceManager.GetString("DisplayName37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Time type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName38 {
            get {
                return ResourceManager.GetString("DisplayName38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI Element に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName39 {
            get {
                return ResourceManager.GetString("DisplayName39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unique constraint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName4 {
            get {
                return ResourceManager.GetString("DisplayName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use coordinate points に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName40 {
            get {
                return ResourceManager.GetString("DisplayName40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   System folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName41 {
            get {
                return ResourceManager.GetString("DisplayName41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Folder path に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName42 {
            get {
                return ResourceManager.GetString("DisplayName42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName43 {
            get {
                return ResourceManager.GetString("DisplayName43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName44 {
            get {
                return ResourceManager.GetString("DisplayName44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName45 {
            get {
                return ResourceManager.GetString("DisplayName45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Result に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName46 {
            get {
                return ResourceManager.GetString("DisplayName46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Beep type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName47 {
            get {
                return ResourceManager.GetString("DisplayName47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Credential name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName48 {
            get {
                return ResourceManager.GetString("DisplayName48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Timeout (ms) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName49 {
            get {
                return ResourceManager.GetString("DisplayName49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The maximum length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName5 {
            get {
                return ResourceManager.GetString("DisplayName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UserName に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName50 {
            get {
                return ResourceManager.GetString("DisplayName50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Error continues to execute に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName51 {
            get {
                return ResourceManager.GetString("DisplayName51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Credential name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName52 {
            get {
                return ResourceManager.GetString("DisplayName52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save type に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName53 {
            get {
                return ResourceManager.GetString("DisplayName53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Default filename に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName54 {
            get {
                return ResourceManager.GetString("DisplayName54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Save as location に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName55 {
            get {
                return ResourceManager.GetString("DisplayName55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Defaults に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName6 {
            get {
                return ResourceManager.GetString("DisplayName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Line filtering mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName7 {
            get {
                return ResourceManager.GetString("DisplayName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column filtering mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName8 {
            get {
                return ResourceManager.GetString("DisplayName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   index に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName9 {
            get {
                return ResourceManager.GetString("DisplayName9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Text must be enclosed in double quotes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubleQuotesHintText {
            get {
                return ResourceManager.GetString("DoubleQuotesHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drag and drop controls here に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DragControlHere {
            get {
                return ResourceManager.GetString("DragControlHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop activity here に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DropActivityHere {
            get {
                return ResourceManager.GetString("DropActivityHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit code に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditCode {
            get {
                return ResourceManager.GetString("EditCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Edit parameter に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditParameter {
            get {
                return ResourceManager.GetString("EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Enter password に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Guide に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GuideText {
            get {
                return ResourceManager.GetString("GuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignored activity に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string IgnoredActivity {
            get {
                return ResourceManager.GetString("IgnoredActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Import parameters に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportParameters {
            get {
                return ResourceManager.GetString("ImportParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Level に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LevelText {
            get {
                return ResourceManager.GetString("LevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   News に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewsText {
            get {
                return ResourceManager.GetString("NewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Reselect に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReselectIt {
            get {
                return ResourceManager.GetString("ReselectIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Special folder に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialFolder {
            get {
                return ResourceManager.GetString("SpecialFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Indicate on screen に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TapScreen {
            get {
                return ResourceManager.GetString("TapScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Workflow file path, must be enclosed in double quotes に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WorkflowFilepathTip {
            get {
                return ResourceManager.GetString("WorkflowFilepathTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Please write a comment in the Text property に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WriteCommentInTextProperty {
            get {
                return ResourceManager.GetString("WriteCommentInTextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   AutoDetect Column Types に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xAutoDetectColType {
            get {
                return ResourceManager.GetString("xAutoDetectColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Auto increment に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xAutoIncrement {
            get {
                return ResourceManager.GetString("xAutoIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Build DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xBuildingDataTable {
            get {
                return ResourceManager.GetString("xBuildingDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xCancel {
            get {
                return ResourceManager.GetString("xCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xCol {
            get {
                return ResourceManager.GetString("xCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Separators に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xColDelimiter {
            get {
                return ResourceManager.GetString("xColDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Editing Wizard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xColEditWizard {
            get {
                return ResourceManager.GetString("xColEditWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column Name に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xColName {
            get {
                return ResourceManager.GetString("xColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Column selection mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xColSelectMode {
            get {
                return ResourceManager.GetString("xColSelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter Wizard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xConfigurationWizard {
            get {
                return ResourceManager.GetString("xConfigurationWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDataSheetInput {
            get {
                return ResourceManager.GetString("xDataSheetInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Datasheet options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDatasheetOption {
            get {
                return ResourceManager.GetString("xDatasheetOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDataSheetOutput {
            get {
                return ResourceManager.GetString("xDataSheetOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable Variable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDataTableFieldHint {
            get {
                return ResourceManager.GetString("xDataTableFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   type of data に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDataType {
            get {
                return ResourceManager.GetString("xDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Defaults に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDefaultVal {
            get {
                return ResourceManager.GetString("xDefaultVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Remove に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDelete {
            get {
                return ResourceManager.GetString("xDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Allowed to be empty に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xEmptyAllowed {
            get {
                return ResourceManager.GetString("xEmptyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Filter Rows に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xFilterRows {
            get {
                return ResourceManager.GetString("xFilterRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Use First Row as Column Headers に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xFirstLineAsHeader {
            get {
                return ResourceManager.GetString("xFirstLineAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Fixed formatting Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xFixedFormatOption {
            get {
                return ResourceManager.GetString("xFixedFormatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ForEach に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xForEach {
            get {
                return ResourceManager.GetString("xForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Formatting Options に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xFormatOption {
            get {
                return ResourceManager.GetString("xFormatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Generate data table に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xGenerateDataTable {
            get {
                return ResourceManager.GetString("xGenerateDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ignore First Row に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xIgnoreFirstLine {
            get {
                return ResourceManager.GetString("xIgnoreFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xIn {
            get {
                return ResourceManager.GetString("xIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sample Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xInputExample {
            get {
                return ResourceManager.GetString("xInputExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xInputTable {
            get {
                return ResourceManager.GetString("xInputTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input DataTable 1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xInputTable1 {
            get {
                return ResourceManager.GetString("xInputTable1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input DataTable 2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xInputTable2 {
            get {
                return ResourceManager.GetString("xInputTable2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Join Wizard に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xJoinTableTitle {
            get {
                return ResourceManager.GetString("xJoinTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Keep に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xKeep {
            get {
                return ResourceManager.GetString("xKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   NewLine Separator に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xLineBreak {
            get {
                return ResourceManager.GetString("xLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   The maximum length に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xMaxLength {
            get {
                return ResourceManager.GetString("xMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   OK に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xOK {
            get {
                return ResourceManager.GetString("xOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Operation に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xOperation {
            get {
                return ResourceManager.GetString("xOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Output column に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xOutputCol {
            get {
                return ResourceManager.GetString("xOutputCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Predefined Columns に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xPredefinedColumns {
            get {
                return ResourceManager.GetString("xPredefinedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xPreview {
            get {
                return ResourceManager.GetString("xPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Test Preview に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xPreviewText {
            get {
                return ResourceManager.GetString("xPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Rows Filtering Mode に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xRowFilteringMode {
            get {
                return ResourceManager.GetString("xRowFilteringMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Unique constraint に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xUniqueConstraint {
            get {
                return ResourceManager.GetString("xUniqueConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Value に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xVal {
            get {
                return ResourceManager.GetString("xVal", resourceCulture);
            }
        }
    }
}
