//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA.Core.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPA.Core.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   UI对象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category1 {
            get {
                return ResourceManager.GetString("Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   凭证选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category10 {
            get {
                return ResourceManager.GetString("Category10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category2 {
            get {
                return ResourceManager.GetString("Category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输入 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category3 {
            get {
                return ResourceManager.GetString("Category3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category4 {
            get {
                return ResourceManager.GetString("Category4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   固定格式选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category5 {
            get {
                return ResourceManager.GetString("Category5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格式化选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category6 {
            get {
                return ResourceManager.GetString("Category6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   开始列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category7 {
            get {
                return ResourceManager.GetString("Category7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   结束列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category8 {
            get {
                return ResourceManager.GetString("Category8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列排序 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Category9 {
            get {
                return ResourceManager.GetString("Category9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Common に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string CommonText {
            get {
                return ResourceManager.GetString("CommonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定即使当前活动失败，也要继续执行其余的活动。只支持布尔值(True,False)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   当前工作目录的路径。这个字段只接受字符串变量。注意:所有字符串变量必须放在引号之间。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description10 {
            get {
                return ResourceManager.GetString("Description10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   从存储在字符串变量中的文件中提取的文本。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description100 {
            get {
                return ResourceManager.GetString("Description100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要写入的文件的路径。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description101 {
            get {
                return ResourceManager.GetString("Description101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要写入文件的文本。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description102 {
            get {
                return ResourceManager.GetString("Description102", resourceCulture);
            }
        }
        
        /// <summary>
        ///    系统中获取的凭据名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description103 {
            get {
                return ResourceManager.GetString("Description103", resourceCulture);
            }
        }
        
        /// <summary>
        ///    指定在引发错误之前等待活动运行的时间量（以毫秒为单位）。默认值为30000毫秒（30秒） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description104 {
            get {
                return ResourceManager.GetString("Description104", resourceCulture);
            }
        }
        
        /// <summary>
        ///    检索到的凭证的安全密码 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description105 {
            get {
                return ResourceManager.GetString("Description105", resourceCulture);
            }
        }
        
        /// <summary>
        ///    检索到的凭证的用户名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description106 {
            get {
                return ResourceManager.GetString("Description106", resourceCulture);
            }
        }
        
        /// <summary>
        ///    指定在引发错误之前等待活动运行的时间量（以毫秒为单位）,默认值为30000毫秒（30秒） に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description107 {
            get {
                return ResourceManager.GetString("Description107", resourceCulture);
            }
        }
        
        /// <summary>
        ///    指定即使活动引发错误, 自动化是否仍应继续 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description108 {
            get {
                return ResourceManager.GetString("Description108", resourceCulture);
            }
        }
        
        /// <summary>
        ///    设置凭证的用户名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description109 {
            get {
                return ResourceManager.GetString("Description109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   可以找到要打开的应用程序的executabel文件的完整路径。注意:所有字符串都必须放在引号之间。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description11 {
            get {
                return ResourceManager.GetString("Description11", resourceCulture);
            }
        }
        
        /// <summary>
        ///    设置凭证的密码 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description110 {
            get {
                return ResourceManager.GetString("Description110", resourceCulture);
            }
        }
        
        /// <summary>
        ///    要更新的凭据名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description111 {
            get {
                return ResourceManager.GetString("Description111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要执行的PowerShell命令。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description112 {
            get {
                return ResourceManager.GetString("Description112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   传递给用于执行命令的管道的编写器的PSObjects的集合。可以是另一个InvokePowerShell活动的输出。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description113 {
            get {
                return ResourceManager.GetString("Description113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   命令执行时返回的一组类型参数objets。可以用于管道几个InvokePowerShell活动。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description114 {
            get {
                return ResourceManager.GetString("Description114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工作流文件路径，必须用双引号括起来 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description115 {
            get {
                return ResourceManager.GetString("Description115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   从剪贴板中检索的数据。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description12 {
            get {
                return ResourceManager.GetString("Description12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要复制到剪贴板的文本。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description13 {
            get {
                return ResourceManager.GetString("Description13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拷贝文件或文件夹 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description14 {
            get {
                return ResourceManager.GetString("Description14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要附加到DataTable的列集合的DataColumn对象。如果设置了此属性，则会忽略“选项”类别下的所有属性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description15 {
            get {
                return ResourceManager.GetString("Description15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   新列的名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description16 {
            get {
                return ResourceManager.GetString("Description16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要添加列的DataTable对象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description17 {
            get {
                return ResourceManager.GetString("Description17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定新列中字段是否允许为空 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description18 {
            get {
                return ResourceManager.GetString("Description18", resourceCulture);
            }
        }
        
        /// <summary>
        ///    指定在添加新行时列的值是否自动递增 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description19 {
            get {
                return ResourceManager.GetString("Description19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   进程名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///    指定新列的每一行中的值必须是唯一的 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description20 {
            get {
                return ResourceManager.GetString("Description20", resourceCulture);
            }
        }
        
        /// <summary>
        ///    指定新列的值的最大长度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description21 {
            get {
                return ResourceManager.GetString("Description21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要添加到DataTable的DataRow对象，如果设置了此属性，则忽略ArrayRow属性。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description22 {
            get {
                return ResourceManager.GetString("Description22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要添加到DataTable的对象数组。每个对象的类型应映射到DataTable中其对应列的类型。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description23 {
            get {
                return ResourceManager.GetString("Description23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要添加行数据的DataTable对象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description24 {
            get {
                return ResourceManager.GetString("Description24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   根据行列信息生成的DataTable表 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description25 {
            get {
                return ResourceManager.GetString("Description25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要清除所有数据的DataTable对象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description26 {
            get {
                return ResourceManager.GetString("Description26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要筛选的DataTable变量。该字段仅支持DataTable变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description27 {
            get {
                return ResourceManager.GetString("Description27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定是否通过保留或删除目标行来过滤表 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description28 {
            get {
                return ResourceManager.GetString("Description28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定是通过保留还是删除目标列来过滤表 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description29 {
            get {
                return ResourceManager.GetString("Description29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   用于在执行活动时查找特定UI元素的Text属性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3 {
            get {
                return ResourceManager.GetString("Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   过滤结果DataTable に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description30 {
            get {
                return ResourceManager.GetString("Description30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   执行单行操作的DataTable变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description31 {
            get {
                return ResourceManager.GetString("Description31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定要转换为表的非结构化数据的来源。该字段仅支持String变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description32 {
            get {
                return ResourceManager.GetString("Description32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   如果使用OCR进行抓取，并且选中了“获取单词信息”复选框，则此字段包含IEnumerable&lt;KeyValuePair&lt;Rectangle,String&gt;&gt;具有WordsInfo值的变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description33 {
            get {
                return ResourceManager.GetString("Description33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定要在表中创建的列的大小。该字段仅支持IEnumerable &lt;Int32&gt;变量。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description34 {
            get {
                return ResourceManager.GetString("Description34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定要用作列分隔符的字符。该字段仅支持String变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description35 {
            get {
                return ResourceManager.GetString("Description35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定要用作换行符分隔符的字符。该字段仅支持String变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description36 {
            get {
                return ResourceManager.GetString("Description36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   选中后，自动检测列或行类型，无论是String，Int32等。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description37 {
            get {
                return ResourceManager.GetString("Description37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   如果选中，则使用第一个标识的列作为列标题 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description38 {
            get {
                return ResourceManager.GetString("Description38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   如果选中，则使用第一个标识的行作为行标题 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description39 {
            get {
                return ResourceManager.GetString("Description39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示当前Windows会话中正在运行的进程的进程对象的集合。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4 {
            get {
                return ResourceManager.GetString("Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成的DataTable变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description40 {
            get {
                return ResourceManager.GetString("Description40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从中检索值的DataRow对象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description41 {
            get {
                return ResourceManager.GetString("Description41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从DataRow检索其值的DataColumn对象。如果设置了此属性，则忽略ColumnName和ColumnIndex属性。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description42 {
            get {
                return ResourceManager.GetString("Description42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从DataRow检索其值的列的索引 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description43 {
            get {
                return ResourceManager.GetString("Description43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从DataRow检索其值的列的名称。如果设置了此属性，则忽略ColumnIndex属性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description44 {
            get {
                return ResourceManager.GetString("Description44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定DataRow的列值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description45 {
            get {
                return ResourceManager.GetString("Description45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要在此操作中使用的第一个表，存储在DataTable变量中。该字段仅支持DataTable变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description46 {
            get {
                return ResourceManager.GetString("Description46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要在此操作中使用的第二个表，存储在DataTable变量中。该字段仅支持DataTable变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description47 {
            get {
                return ResourceManager.GetString("Description47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要在其中执行查找的DataTable变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description48 {
            get {
                return ResourceManager.GetString("Description48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要在指定DataTable变量中搜索的值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description49 {
            get {
                return ResourceManager.GetString("Description49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   描述要关闭的流程的流程类型对象。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description5 {
            get {
                return ResourceManager.GetString("Description5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从DataRow检索其值的DataColumn对象。在此属性字段中设置变量会禁用其他两个属性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description50 {
            get {
                return ResourceManager.GetString("Description50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从DataRow检索其值的列的索引。在此属性字段中设置变量会禁用其他两个属性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description51 {
            get {
                return ResourceManager.GetString("Description51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从DataRow检索其值的列的名称。在此属性字段中设置变量会禁用其他两个属性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description52 {
            get {
                return ResourceManager.GetString("Description52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返回在此列与RowIndex属性中的值之间的坐标处找到的单元格 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description53 {
            get {
                return ResourceManager.GetString("Description53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返回在此列与RowIndex属性值之间的坐标处找到的单元格的列索引 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description54 {
            get {
                return ResourceManager.GetString("Description54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   返回在此列与RowIndex属性中的值之间的坐标处找到的单元格的列名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description55 {
            get {
                return ResourceManager.GetString("Description55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   单元格中找到的值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description56 {
            get {
                return ResourceManager.GetString("Description56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   单元格的Row索引 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description57 {
            get {
                return ResourceManager.GetString("Description57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合并源DataTable的DataTable对象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description58 {
            get {
                return ResourceManager.GetString("Description58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要添加到目标DataTable的DataTable对象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description59 {
            get {
                return ResourceManager.GetString("Description59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要关闭的进程的名称。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description6 {
            get {
                return ResourceManager.GetString("Description6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定合并两个DataTable时要执行的操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description60 {
            get {
                return ResourceManager.GetString("Description60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要写入字符串的DataTable对象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description61 {
            get {
                return ResourceManager.GetString("Description61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable作为字符串的输出 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description62 {
            get {
                return ResourceManager.GetString("Description62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从中删除列的DataTable对象 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description63 {
            get {
                return ResourceManager.GetString("Description63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从DataTable的列集合中删除的DataColumn对象。如果设置了此属性，则忽略其它两个列索引选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description64 {
            get {
                return ResourceManager.GetString("Description64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从DataTable的列集合中删除的列的索引。如果设置了此属性，则忽略其它两个列索引选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description65 {
            get {
                return ResourceManager.GetString("Description65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从DataTable的列集合中删除的列的名称。如果设置了此属性，则忽略其它两个列索引选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description66 {
            get {
                return ResourceManager.GetString("Description66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要删除的DataRow对象。如果设置了此属性，则忽略行索引选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description67 {
            get {
                return ResourceManager.GetString("Description67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要删除的行的索引。如果设置了此属性，则忽略DataRow索引选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description68 {
            get {
                return ResourceManager.GetString("Description68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要从中删除重复行的DataTable变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description69 {
            get {
                return ResourceManager.GetString("Description69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定在抛出错误之前等待活动运行的时间(以毫秒为单位)。默认值为3000毫秒(3秒)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description7 {
            get {
                return ResourceManager.GetString("Description7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输出已删除重复行的DataTable，存储在DataTable变量中。放置与Input字段中的变量相同的变量会更改初始变量，而提供新变量会使初始变量不受影响。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description70 {
            get {
                return ResourceManager.GetString("Description70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要排序的DataTable变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description71 {
            get {
                return ResourceManager.GetString("Description71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   按其排序的列的变量。该字段仅支持DataColumn变量。在此属性字段中设置变量会禁用其他两个属性 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description72 {
            get {
                return ResourceManager.GetString("Description72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排序后的DataTable变量。放置与Input字段中的变量相同的变量会更改初始变量，而添加新变量会使初始变量不受影响。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description73 {
            get {
                return ResourceManager.GetString("Description73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输入UIElement に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description74 {
            get {
                return ResourceManager.GetString("Description74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   弹出窗口的文本。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description75 {
            get {
                return ResourceManager.GetString("Description75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   弹出窗口的标题。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description76 {
            get {
                return ResourceManager.GetString("Description76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   持续时间，直到弹出窗口自动关闭。默认情况下，弹出窗口不会关闭。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description77 {
            get {
                return ResourceManager.GetString("Description77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   这表示HTML文件的完整路径或外部URL。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description78 {
            get {
                return ResourceManager.GetString("Description78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   提供的HTML页面返回的字符串。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description79 {
            get {
                return ResourceManager.GetString("Description79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   可以在启动时传递给应用程序的参数。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description8 {
            get {
                return ResourceManager.GetString("Description8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表单字段的标签。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description80 {
            get {
                return ResourceManager.GetString("Description80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   可供选择的选项数组。如果将其设置为只包含一个元素，则会出现一个文本框来编写文本。如果将其设置为包含2或3个元素，则它们将显示为要从中选择的单选按钮。如果将其设置为包含3个以上的项，则它们将作为组合框显示以供选择。此字段只支持字符串数组变量。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description81 {
            get {
                return ResourceManager.GetString("Description81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输入对话框的标题。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description82 {
            get {
                return ResourceManager.GetString("Description82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   用户在输入对话框中插入的值。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description83 {
            get {
                return ResourceManager.GetString("Description83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消息框对话框的标题。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description84 {
            get {
                return ResourceManager.GetString("Description84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要显示在消息框中的文本。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description85 {
            get {
                return ResourceManager.GetString("Description85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   表示消息框对话框中按下的按钮的字符串。它可以是:Ok,Yes,No或Cancel に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description86 {
            get {
                return ResourceManager.GetString("Description86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文件的路径。如果路径不完整，则在项目文件夹中创建文件。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description87 {
            get {
                return ResourceManager.GetString("Description87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要附加到文件中的文本。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description88 {
            get {
                return ResourceManager.GetString("Description88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要复制的文件的路径。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description89 {
            get {
                return ResourceManager.GetString("Description89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   可以找到要打开的应用程序的可执行文件的完整文件路径。注意:所有字符串都必须放在引号之间。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description9 {
            get {
                return ResourceManager.GetString("Description9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要复制文件的目标路径。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description90 {
            get {
                return ResourceManager.GetString("Description90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要创建的目录的完整路径。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description91 {
            get {
                return ResourceManager.GetString("Description91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要创建的文件的名称。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description92 {
            get {
                return ResourceManager.GetString("Description92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要创建的文件的完整路径。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description93 {
            get {
                return ResourceManager.GetString("Description93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要永久删除的文件或目录的路径。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description94 {
            get {
                return ResourceManager.GetString("Description94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要移动的文件的路径。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description95 {
            get {
                return ResourceManager.GetString("Description95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要移动文件的目标路径。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description96 {
            get {
                return ResourceManager.GetString("Description96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要检查的完整路径。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description97 {
            get {
                return ResourceManager.GetString("Description97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   声明是否找到文档或文件。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description98 {
            get {
                return ResourceManager.GetString("Description98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   要读取的文件的路径。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description99 {
            get {
                return ResourceManager.GetString("Description99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   窗口指示器 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName1 {
            get {
                return ResourceManager.GetString("DisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName10 {
            get {
                return ResourceManager.GetString("DisplayName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列宽 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName11 {
            get {
                return ResourceManager.GetString("DisplayName11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列分隔符 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName12 {
            get {
                return ResourceManager.GetString("DisplayName12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行分隔符 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName13 {
            get {
                return ResourceManager.GetString("DisplayName13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   CSV解析 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName14 {
            get {
                return ResourceManager.GetString("DisplayName14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   类型自动检测 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName15 {
            get {
                return ResourceManager.GetString("DisplayName15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列标题 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName16 {
            get {
                return ResourceManager.GetString("DisplayName16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行标题 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName17 {
            get {
                return ResourceManager.GetString("DisplayName17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName18 {
            get {
                return ResourceManager.GetString("DisplayName18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName19 {
            get {
                return ResourceManager.GetString("DisplayName19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   允许为空 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName2 {
            get {
                return ResourceManager.GetString("DisplayName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列索引 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName20 {
            get {
                return ResourceManager.GetString("DisplayName20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName21 {
            get {
                return ResourceManager.GetString("DisplayName21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName22 {
            get {
                return ResourceManager.GetString("DisplayName22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName23 {
            get {
                return ResourceManager.GetString("DisplayName23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName24 {
            get {
                return ResourceManager.GetString("DisplayName24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   JoinType に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName25 {
            get {
                return ResourceManager.GetString("DisplayName25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName26 {
            get {
                return ResourceManager.GetString("DisplayName26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   单元格值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName27 {
            get {
                return ResourceManager.GetString("DisplayName27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行索引 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName28 {
            get {
                return ResourceManager.GetString("DisplayName28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   目标 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName29 {
            get {
                return ResourceManager.GetString("DisplayName29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自动递增 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName3 {
            get {
                return ResourceManager.GetString("DisplayName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   源 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName30 {
            get {
                return ResourceManager.GetString("DisplayName30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   合并操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName31 {
            get {
                return ResourceManager.GetString("DisplayName31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文本 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName32 {
            get {
                return ResourceManager.GetString("DisplayName32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName33 {
            get {
                return ResourceManager.GetString("DisplayName33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   排序 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName34 {
            get {
                return ResourceManager.GetString("DisplayName34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   日期时间 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName35 {
            get {
                return ResourceManager.GetString("DisplayName35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   转换类型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName36 {
            get {
                return ResourceManager.GetString("DisplayName36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   时间 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName37 {
            get {
                return ResourceManager.GetString("DisplayName37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   时间类型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName38 {
            get {
                return ResourceManager.GetString("DisplayName38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   UI元素 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName39 {
            get {
                return ResourceManager.GetString("DisplayName39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   唯一约束 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName4 {
            get {
                return ResourceManager.GetString("DisplayName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   使用坐标点 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName40 {
            get {
                return ResourceManager.GetString("DisplayName40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   系统文件夹 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName41 {
            get {
                return ResourceManager.GetString("DisplayName41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文件夹路径 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName42 {
            get {
                return ResourceManager.GetString("DisplayName42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   变量名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName43 {
            get {
                return ResourceManager.GetString("DisplayName43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   变量值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName44 {
            get {
                return ResourceManager.GetString("DisplayName44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   密码 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName45 {
            get {
                return ResourceManager.GetString("DisplayName45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   结果 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName46 {
            get {
                return ResourceManager.GetString("DisplayName46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   提示音类型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName47 {
            get {
                return ResourceManager.GetString("DisplayName47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   凭据名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName48 {
            get {
                return ResourceManager.GetString("DisplayName48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   超时时间(毫秒) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName49 {
            get {
                return ResourceManager.GetString("DisplayName49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大长度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName5 {
            get {
                return ResourceManager.GetString("DisplayName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   用户名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName50 {
            get {
                return ResourceManager.GetString("DisplayName50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   错误继续执行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName51 {
            get {
                return ResourceManager.GetString("DisplayName51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   凭证名称 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName52 {
            get {
                return ResourceManager.GetString("DisplayName52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保存类型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName53 {
            get {
                return ResourceManager.GetString("DisplayName53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   默认文件名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName54 {
            get {
                return ResourceManager.GetString("DisplayName54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   另存为位置 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName55 {
            get {
                return ResourceManager.GetString("DisplayName55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   默认值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName6 {
            get {
                return ResourceManager.GetString("DisplayName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行过滤模式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName7 {
            get {
                return ResourceManager.GetString("DisplayName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列过滤模式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName8 {
            get {
                return ResourceManager.GetString("DisplayName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   索引 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DisplayName9 {
            get {
                return ResourceManager.GetString("DisplayName9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Do に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Do {
            get {
                return ResourceManager.GetString("Do", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文本必须用双引号括起来 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DoubleQuotesHintText {
            get {
                return ResourceManager.GetString("DoubleQuotesHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   拖放控件到这里 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DragControlHere {
            get {
                return ResourceManager.GetString("DragControlHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Drop activity here に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string DropActivityHere {
            get {
                return ResourceManager.GetString("DropActivityHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   编辑代码 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditCode {
            get {
                return ResourceManager.GetString("EditCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   编辑参数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditParameter {
            get {
                return ResourceManager.GetString("EditParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输入密码 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EnterPassword {
            get {
                return ResourceManager.GetString("EnterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   向导 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string GuideText {
            get {
                return ResourceManager.GetString("GuideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   导入参数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ImportParameters {
            get {
                return ResourceManager.GetString("ImportParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Input に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string InputText {
            get {
                return ResourceManager.GetString("InputText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   级别 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string LevelText {
            get {
                return ResourceManager.GetString("LevelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   消息 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string NewsText {
            get {
                return ResourceManager.GetString("NewsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   重新选取 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string ReselectIt {
            get {
                return ResourceManager.GetString("ReselectIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   特殊文件夹 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SpecialFolder {
            get {
                return ResourceManager.GetString("SpecialFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   点击屏幕 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string TapScreen {
            get {
                return ResourceManager.GetString("TapScreen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   工作流文件路径，必须用双引号括起来 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string WorkflowFilepathTip {
            get {
                return ResourceManager.GetString("WorkflowFilepathTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自动检测列类型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xAutoDetectColType {
            get {
                return ResourceManager.GetString("xAutoDetectColType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   自动递增 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xAutoIncrement {
            get {
                return ResourceManager.GetString("xAutoIncrement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   构建数据表 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xBuildingDataTable {
            get {
                return ResourceManager.GetString("xBuildingDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   取消 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xCancel {
            get {
                return ResourceManager.GetString("xCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xCol {
            get {
                return ResourceManager.GetString("xCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列分隔符 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xColDelimiter {
            get {
                return ResourceManager.GetString("xColDelimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列编辑向导 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xColEditWizard {
            get {
                return ResourceManager.GetString("xColEditWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列名 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xColName {
            get {
                return ResourceManager.GetString("xColName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   列选择模式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xColSelectMode {
            get {
                return ResourceManager.GetString("xColSelectMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配置向导 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xConfigurationWizard {
            get {
                return ResourceManager.GetString("xConfigurationWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数据表(输入) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDataSheetInput {
            get {
                return ResourceManager.GetString("xDataSheetInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数据表选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDatasheetOption {
            get {
                return ResourceManager.GetString("xDatasheetOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数据表(输出) に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDataSheetOutput {
            get {
                return ResourceManager.GetString("xDataSheetOutput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   DataTable变量 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDataTableFieldHint {
            get {
                return ResourceManager.GetString("xDataTableFieldHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数据类型 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDataType {
            get {
                return ResourceManager.GetString("xDataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   默认值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDefaultVal {
            get {
                return ResourceManager.GetString("xDefaultVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   删除 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xDelete {
            get {
                return ResourceManager.GetString("xDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   允许为空 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xEmptyAllowed {
            get {
                return ResourceManager.GetString("xEmptyAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   过滤行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xFilterRows {
            get {
                return ResourceManager.GetString("xFilterRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   首行作数据表头 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xFirstLineAsHeader {
            get {
                return ResourceManager.GetString("xFirstLineAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   固定格式选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xFixedFormatOption {
            get {
                return ResourceManager.GetString("xFixedFormatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ForEach に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xForEach {
            get {
                return ResourceManager.GetString("xForEach", resourceCulture);
            }
        }
        
        /// <summary>
        ///   格式选项 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xFormatOption {
            get {
                return ResourceManager.GetString("xFormatOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   生成数据表 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xGenerateDataTable {
            get {
                return ResourceManager.GetString("xGenerateDataTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   忽略首行 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xIgnoreFirstLine {
            get {
                return ResourceManager.GetString("xIgnoreFirstLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   in に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xIn {
            get {
                return ResourceManager.GetString("xIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输入示例 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xInputExample {
            get {
                return ResourceManager.GetString("xInputExample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输入数据表 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xInputTable {
            get {
                return ResourceManager.GetString("xInputTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输入数据表1 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xInputTable1 {
            get {
                return ResourceManager.GetString("xInputTable1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输入数据表2 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xInputTable2 {
            get {
                return ResourceManager.GetString("xInputTable2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   附加数据表 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xJoinTableTitle {
            get {
                return ResourceManager.GetString("xJoinTableTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   保留 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xKeep {
            get {
                return ResourceManager.GetString("xKeep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   换行符 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xLineBreak {
            get {
                return ResourceManager.GetString("xLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   最大长度 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xMaxLength {
            get {
                return ResourceManager.GetString("xMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   确定 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xOK {
            get {
                return ResourceManager.GetString("xOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   操作 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xOperation {
            get {
                return ResourceManager.GetString("xOperation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   输出列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xOutputCol {
            get {
                return ResourceManager.GetString("xOutputCol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   预定义列 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xPredefinedColumns {
            get {
                return ResourceManager.GetString("xPredefinedColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   预览 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xPreview {
            get {
                return ResourceManager.GetString("xPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   预览测试 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xPreviewText {
            get {
                return ResourceManager.GetString("xPreviewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   行过滤模式 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xRowFilteringMode {
            get {
                return ResourceManager.GetString("xRowFilteringMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   唯一约束 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xUniqueConstraint {
            get {
                return ResourceManager.GetString("xUniqueConstraint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   值 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string xVal {
            get {
                return ResourceManager.GetString("xVal", resourceCulture);
            }
        }
    }
}
