//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA.Script.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPA.Script.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   すべてについて、現在のスレッドの CurrentUICulture プロパティをオーバーライドします
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Python脚本文件路径，必须用双引号括起来 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Python脚本文件执行时的工作目录，默认为当前项目目录 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   指定即使当前活动失败，也要继续执行其余的活动。只支持布尔值(True,False)。 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description3 {
            get {
                return ResourceManager.GetString("Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Python脚本代码执行时的工作目录，默认为当前项目目录 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string Description4 {
            get {
                return ResourceManager.GetString("Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   编辑代码 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditCode {
            get {
                return ResourceManager.GetString("EditCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   编辑参数 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string EditParameters {
            get {
                return ResourceManager.GetString("EditParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Python脚本文件路径，必须用双引号括起来 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string PythonPathHintText {
            get {
                return ResourceManager.GetString("PythonPathHintText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   设置工作目录 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetWorkingDirectory {
            get {
                return ResourceManager.GetString("SetWorkingDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   默认工作目录为当前项目目录 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        public static string SetWorkingDirectoryTip {
            get {
                return ResourceManager.GetString("SetWorkingDirectoryTip", resourceCulture);
            }
        }
    }
}
