//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace RPA.Integration.Activities.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RPA.Integration.Activities.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 添加 的本地化字符串。
        /// </summary>
        public static string AddText {
            get {
                return ResourceManager.GetString("AddText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接配置 的本地化字符串。
        /// </summary>
        public static string Category1 {
            get {
                return ResourceManager.GetString("Category1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体设置 的本地化字符串。
        /// </summary>
        public static string Category10 {
            get {
                return ResourceManager.GetString("Category10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行高列宽 的本地化字符串。
        /// </summary>
        public static string Category11 {
            get {
                return ResourceManager.GetString("Category11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框 的本地化字符串。
        /// </summary>
        public static string Category12 {
            get {
                return ResourceManager.GetString("Category12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 服务器 的本地化字符串。
        /// </summary>
        public static string Category13 {
            get {
                return ResourceManager.GetString("Category13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 凭据 的本地化字符串。
        /// </summary>
        public static string Category14 {
            get {
                return ResourceManager.GetString("Category14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全设置 的本地化字符串。
        /// </summary>
        public static string Category15 {
            get {
                return ResourceManager.GetString("Category15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登录 的本地化字符串。
        /// </summary>
        public static string Category16 {
            get {
                return ResourceManager.GetString("Category16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 筛选 的本地化字符串。
        /// </summary>
        public static string Category17 {
            get {
                return ResourceManager.GetString("Category17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 寄件人 的本地化字符串。
        /// </summary>
        public static string Category18 {
            get {
                return ResourceManager.GetString("Category18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 收件人 的本地化字符串。
        /// </summary>
        public static string Category19 {
            get {
                return ResourceManager.GetString("Category19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出 的本地化字符串。
        /// </summary>
        public static string Category2 {
            get {
                return ResourceManager.GetString("Category2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件 的本地化字符串。
        /// </summary>
        public static string Category20 {
            get {
                return ResourceManager.GetString("Category20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件 的本地化字符串。
        /// </summary>
        public static string Category21 {
            get {
                return ResourceManager.GetString("Category21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转发 的本地化字符串。
        /// </summary>
        public static string Category22 {
            get {
                return ResourceManager.GetString("Category22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 方向 的本地化字符串。
        /// </summary>
        public static string Category23 {
            get {
                return ResourceManager.GetString("Category23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面属性 的本地化字符串。
        /// </summary>
        public static string Category24 {
            get {
                return ResourceManager.GetString("Category24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 页面边距 的本地化字符串。
        /// </summary>
        public static string Category25 {
            get {
                return ResourceManager.GetString("Category25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片 的本地化字符串。
        /// </summary>
        public static string Category26 {
            get {
                return ResourceManager.GetString("Category26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 书签 的本地化字符串。
        /// </summary>
        public static string Category27 {
            get {
                return ResourceManager.GetString("Category27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超链接 的本地化字符串。
        /// </summary>
        public static string Category28 {
            get {
                return ResourceManager.GetString("Category28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 断开连接 的本地化字符串。
        /// </summary>
        public static string Category3 {
            get {
                return ResourceManager.GetString("Category3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格选项 的本地化字符串。
        /// </summary>
        public static string Category30 {
            get {
                return ResourceManager.GetString("Category30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作表选项 的本地化字符串。
        /// </summary>
        public static string Category31 {
            get {
                return ResourceManager.GetString("Category31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格起始 的本地化字符串。
        /// </summary>
        public static string Category32 {
            get {
                return ResourceManager.GetString("Category32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格结束 的本地化字符串。
        /// </summary>
        public static string Category33 {
            get {
                return ResourceManager.GetString("Category33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格终点 的本地化字符串。
        /// </summary>
        public static string Category34 {
            get {
                return ResourceManager.GetString("Category34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区域选项 的本地化字符串。
        /// </summary>
        public static string Category35 {
            get {
                return ResourceManager.GetString("Category35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换选项 的本地化字符串。
        /// </summary>
        public static string Category36 {
            get {
                return ResourceManager.GetString("Category36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行列数选项 的本地化字符串。
        /// </summary>
        public static string Category37 {
            get {
                return ResourceManager.GetString("Category37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开/新建文档选项 的本地化字符串。
        /// </summary>
        public static string Category38 {
            get {
                return ResourceManager.GetString("Category38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 选项 的本地化字符串。
        /// </summary>
        public static string Category4 {
            get {
                return ResourceManager.GetString("Category4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入 的本地化字符串。
        /// </summary>
        public static string Category5 {
            get {
                return ResourceManager.GetString("Category5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建/打开文档选项 的本地化字符串。
        /// </summary>
        public static string Category6 {
            get {
                return ResourceManager.GetString("Category6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存选项 的本地化字符串。
        /// </summary>
        public static string Category7 {
            get {
                return ResourceManager.GetString("Category7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴选项 的本地化字符串。
        /// </summary>
        public static string Category8 {
            get {
                return ResourceManager.GetString("Category8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制选项 的本地化字符串。
        /// </summary>
        public static string Category9 {
            get {
                return ResourceManager.GetString("Category9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 配置数据库连接 的本地化字符串。
        /// </summary>
        public static string ConfigureDatabaseConnection {
            get {
                return ResourceManager.GetString("ConfigureDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接配置 的本地化字符串。
        /// </summary>
        public static string ConnectionConfiguration {
            get {
                return ResourceManager.GetString("ConnectionConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接设置 的本地化字符串。
        /// </summary>
        public static string ConnectionSettings {
            get {
                return ResourceManager.GetString("ConnectionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接向导 的本地化字符串。
        /// </summary>
        public static string ConnectionWizard {
            get {
                return ResourceManager.GetString("ConnectionWizard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容 的本地化字符串。
        /// </summary>
        public static string ContentText {
            get {
                return ResourceManager.GetString("ContentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 删除 的本地化字符串。
        /// </summary>
        public static string DeleteText {
            get {
                return ResourceManager.GetString("DeleteText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于建立数据库连接的连接字符串 的本地化字符串。
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定如何解释命令字符串 的本地化字符串。
        /// </summary>
        public static string Description10 {
            get {
                return ResourceManager.GetString("Description10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行的SQL命令语句 的本地化字符串。
        /// </summary>
        public static string Description11 {
            get {
                return ResourceManager.GetString("Description11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对于UPDATE，INSERT和DELETE语句，返回值是受命令影响的行数。对于所有其他类型的语句，返回值为-1 的本地化字符串。
        /// </summary>
        public static string Description12 {
            get {
                return ResourceManager.GetString("Description12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将SQL查询的输出存储在DataTable变量中 的本地化字符串。
        /// </summary>
        public static string Description13 {
            get {
                return ResourceManager.GetString("Description13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定此活动中的数据库操作是否应包装在数据库事务中 的本地化字符串。
        /// </summary>
        public static string Description14 {
            get {
                return ResourceManager.GetString("Description14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行活动后的延迟时间(以毫秒为单位)。默认时间为3000毫秒。 的本地化字符串。
        /// </summary>
        public static string Description15 {
            get {
                return ResourceManager.GetString("Description15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 延迟活动开始执行任何操作之前的时间(以毫秒为单位)。默认时间为0毫秒。 的本地化字符串。
        /// </summary>
        public static string Description16 {
            get {
                return ResourceManager.GetString("Description16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴单元格区域的起始单元格 的本地化字符串。
        /// </summary>
        public static string Description17 {
            get {
                return ResourceManager.GetString("Description17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴单元格区域的工作薄名称 的本地化字符串。
        /// </summary>
        public static string Description18 {
            get {
                return ResourceManager.GetString("Description18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存储读取数据的DataTable 的本地化字符串。
        /// </summary>
        public static string Description19 {
            get {
                return ResourceManager.GetString("Description19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于访问数据库的数据库提供程序的名称 的本地化字符串。
        /// </summary>
        public static string Description2 {
            get {
                return ResourceManager.GetString("Description2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入数据的DataTable变量名 的本地化字符串。
        /// </summary>
        public static string Description20 {
            get {
                return ResourceManager.GetString("Description20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于发送邮件的电子邮件帐户 的本地化字符串。
        /// </summary>
        public static string Description21 {
            get {
                return ResourceManager.GetString("Description21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于发送邮件的电子邮件帐户的密码 的本地化字符串。
        /// </summary>
        public static string Description22 {
            get {
                return ResourceManager.GetString("Description22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用的电子邮件服务器主机 的本地化字符串。
        /// </summary>
        public static string Description23 {
            get {
                return ResourceManager.GetString("Description23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件将通过的端口 的本地化字符串。
        /// </summary>
        public static string Description24 {
            get {
                return ResourceManager.GetString("Description24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索消息的邮件文件夹 的本地化字符串。
        /// </summary>
        public static string Description25 {
            get {
                return ResourceManager.GetString("Description25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定用于连接的SSL和/或TLS加密 的本地化字符串。
        /// </summary>
        public static string Description26 {
            get {
                return ResourceManager.GetString("Description26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从列表顶部开始检索的消息数 的本地化字符串。
        /// </summary>
        public static string Description27 {
            get {
                return ResourceManager.GetString("Description27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  指定是否应将读取的消息标记为删除 的本地化字符串。
        /// </summary>
        public static string Description28 {
            get {
                return ResourceManager.GetString("Description28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定是否将检索到的消息标记为已读 的本地化字符串。
        /// </summary>
        public static string Description29 {
            get {
                return ResourceManager.GetString("Description29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 数据库连接 的本地化字符串。
        /// </summary>
        public static string Description3 {
            get {
                return ResourceManager.GetString("Description3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定是否仅检索未读消息 的本地化字符串。
        /// </summary>
        public static string Description30 {
            get {
                return ResourceManager.GetString("Description30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据邮件主题筛选相应的邮件 的本地化字符串。
        /// </summary>
        public static string Description31 {
            get {
                return ResourceManager.GetString("Description31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据发件人地址筛选相应的邮件 的本地化字符串。
        /// </summary>
        public static string Description32 {
            get {
                return ResourceManager.GetString("Description32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 根据邮件超文本内容筛选相应的邮件 的本地化字符串。
        /// </summary>
        public static string Description33 {
            get {
                return ResourceManager.GetString("Description33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将检索到的消息作为MailMessage对象的集合 的本地化字符串。
        /// </summary>
        public static string Description34 {
            get {
                return ResourceManager.GetString("Description34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于提取图片的邮件，该字段仅支持MimeMessage变量 的本地化字符串。
        /// </summary>
        public static string Description35 {
            get {
                return ResourceManager.GetString("Description35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将邮件中的邮件存储到本地目录,为空则不保存 的本地化字符串。
        /// </summary>
        public static string Description36 {
            get {
                return ResourceManager.GetString("Description36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片本地保存路径列表 的本地化字符串。
        /// </summary>
        public static string Description37 {
            get {
                return ResourceManager.GetString("Description37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存图片信息，分为地址和base64码两种方式 的本地化字符串。
        /// </summary>
        public static string Description38 {
            get {
                return ResourceManager.GetString("Description38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定是否应使用SSL发送消息 的本地化字符串。
        /// </summary>
        public static string Description39 {
            get {
                return ResourceManager.GetString("Description39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要关闭的数据库连接(DatabaseConnection变量) 的本地化字符串。
        /// </summary>
        public static string Description4 {
            get {
                return ResourceManager.GetString("Description4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要将消息移动到的邮件文件夹 的本地化字符串。
        /// </summary>
        public static string Description40 {
            get {
                return ResourceManager.GetString("Description40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 可以找到邮件消息的文件夹 的本地化字符串。
        /// </summary>
        public static string Description41 {
            get {
                return ResourceManager.GetString("Description41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要移动的MailMessage对象 的本地化字符串。
        /// </summary>
        public static string Description42 {
            get {
                return ResourceManager.GetString("Description42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要保存MailMessage对象的完整路径 的本地化字符串。
        /// </summary>
        public static string Description43 {
            get {
                return ResourceManager.GetString("Description43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要保存的MailMessage对象 的本地化字符串。
        /// </summary>
        public static string Description44 {
            get {
                return ResourceManager.GetString("Description44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要保存MimeMessage附件的完整路径 的本地化字符串。
        /// </summary>
        public static string Description45 {
            get {
                return ResourceManager.GetString("Description45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要保存的MimeMessage附件 的本地化字符串。
        /// </summary>
        public static string Description46 {
            get {
                return ResourceManager.GetString("Description46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索到的附件 的本地化字符串。
        /// </summary>
        public static string Description47 {
            get {
                return ResourceManager.GetString("Description47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发件人的显示名称 的本地化字符串。
        /// </summary>
        public static string Description48 {
            get {
                return ResourceManager.GetString("Description48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发件人的电子邮件地址 的本地化字符串。
        /// </summary>
        public static string Description49 {
            get {
                return ResourceManager.GetString("Description49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定浏览器响应超时时间(毫秒) 的本地化字符串。
        /// </summary>
        public static string Description5 {
            get {
                return ResourceManager.GetString("Description5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件的主要收件人 的本地化字符串。
        /// </summary>
        public static string Description50 {
            get {
                return ResourceManager.GetString("Description50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件的次要收件人 的本地化字符串。
        /// </summary>
        public static string Description51 {
            get {
                return ResourceManager.GetString("Description51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件的隐藏收件人 的本地化字符串。
        /// </summary>
        public static string Description52 {
            get {
                return ResourceManager.GetString("Description52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件的主题 的本地化字符串。
        /// </summary>
        public static string Description53 {
            get {
                return ResourceManager.GetString("Description53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 电子邮件的正文 的本地化字符串。
        /// </summary>
        public static string Description54 {
            get {
                return ResourceManager.GetString("Description54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件的优先级标志 的本地化字符串。
        /// </summary>
        public static string Description55 {
            get {
                return ResourceManager.GetString("Description55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  指定邮件正文是否以HTML格式编写 的本地化字符串。
        /// </summary>
        public static string Description56 {
            get {
                return ResourceManager.GetString("Description56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要添加到电子邮件中的附件 的本地化字符串。
        /// </summary>
        public static string Description57 {
            get {
                return ResourceManager.GetString("Description57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要转发的消息,该字段仅支持MailMessage对象 的本地化字符串。
        /// </summary>
        public static string Description58 {
            get {
                return ResourceManager.GetString("Description58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outlook数据文件的保存路径 的本地化字符串。
        /// </summary>
        public static string Description59 {
            get {
                return ResourceManager.GetString("Description59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 出现错误是否继续执行 的本地化字符串。
        /// </summary>
        public static string Description6 {
            get {
                return ResourceManager.GetString("Description6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outlook账户名 的本地化字符串。
        /// </summary>
        public static string Description60 {
            get {
                return ResourceManager.GetString("Description60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 指定邮件对象 的本地化字符串。
        /// </summary>
        public static string Description61 {
            get {
                return ResourceManager.GetString("Description61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似  指定在引发错误之前等待活动运行的时间量（以毫秒为单位）。默认值为30000毫秒（30秒） 的本地化字符串。
        /// </summary>
        public static string Description62 {
            get {
                return ResourceManager.GetString("Description62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 从哪个邮件目录去获取邮件 的本地化字符串。
        /// </summary>
        public static string Description63 {
            get {
                return ResourceManager.GetString("Description63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只有符合过滤条件的邮件才会被获取 的本地化字符串。
        /// </summary>
        public static string Description64 {
            get {
                return ResourceManager.GetString("Description64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否只获取未读邮件，默认打勾 的本地化字符串。
        /// </summary>
        public static string Description65 {
            get {
                return ResourceManager.GetString("Description65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否将接收到的邮件自动标记成已读 的本地化字符串。
        /// </summary>
        public static string Description66 {
            get {
                return ResourceManager.GetString("Description66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Outlook邮件目录 的本地化字符串。
        /// </summary>
        public static string Description67 {
            get {
                return ResourceManager.GetString("Description67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不勾选的话只回复给发送者，勾选的话不仅给发送者，还会给所有抄送者回复邮件 的本地化字符串。
        /// </summary>
        public static string Description68 {
            get {
                return ResourceManager.GetString("Description68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件的保存路径 的本地化字符串。
        /// </summary>
        public static string Description69 {
            get {
                return ResourceManager.GetString("Description69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 插入表中的DataTable变量。DataTable列的名称和描述必须与数据库表中的名称和描述相匹配 的本地化字符串。
        /// </summary>
        public static string Description7 {
            get {
                return ResourceManager.GetString("Description7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出附件列表 的本地化字符串。
        /// </summary>
        public static string Description70 {
            get {
                return ResourceManager.GetString("Description70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正则表达式过滤器，只有符合过滤条件的附件名才会被保存 的本地化字符串。
        /// </summary>
        public static string Description71 {
            get {
                return ResourceManager.GetString("Description71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 预期的显示名称，邮件系统必须支持该功能才能使用 的本地化字符串。
        /// </summary>
        public static string Description72 {
            get {
                return ResourceManager.GetString("Description72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取到Word文档中的全部内容文字 的本地化字符串。
        /// </summary>
        public static string Description73 {
            get {
                return ResourceManager.GetString("Description73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 写入文本前写入的行数 的本地化字符串。
        /// </summary>
        public static string Description74 {
            get {
                return ResourceManager.GetString("Description74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代表单元格名称的VB表达式，如A1 的本地化字符串。
        /// </summary>
        public static string Description76 {
            get {
                return ResourceManager.GetString("Description76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 为空代表当前活动工作表 的本地化字符串。
        /// </summary>
        public static string Description77 {
            get {
                return ResourceManager.GetString("Description77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代表单元格名称的VB表达式，如B2 的本地化字符串。
        /// </summary>
        public static string Description78 {
            get {
                return ResourceManager.GetString("Description78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作表中有效行数 的本地化字符串。
        /// </summary>
        public static string Description79 {
            get {
                return ResourceManager.GetString("Description79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 要在其中插入数据的SQL表 的本地化字符串。
        /// </summary>
        public static string Description8 {
            get {
                return ResourceManager.GetString("Description8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代表单元格名称的VB表达式，如A1 的本地化字符串。
        /// </summary>
        public static string Description80 {
            get {
                return ResourceManager.GetString("Description80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 代表单元格名称的VB表达式，如B2 的本地化字符串。
        /// </summary>
        public static string Description81 {
            get {
                return ResourceManager.GetString("Description81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 将受影响的行数存储到Int32变量中 的本地化字符串。
        /// </summary>
        public static string Description9 {
            get {
                return ResourceManager.GetString("Description9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 连接字符串 的本地化字符串。
        /// </summary>
        public static string DisplayName1 {
            get {
                return ResourceManager.GetString("DisplayName1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        public static string DisplayName10 {
            get {
                return ResourceManager.GetString("DisplayName10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户 的本地化字符串。
        /// </summary>
        public static string DisplayName100 {
            get {
                return ResourceManager.GetString("DisplayName100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 过滤器 的本地化字符串。
        /// </summary>
        public static string DisplayName101 {
            get {
                return ResourceManager.GetString("DisplayName101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取附件 的本地化字符串。
        /// </summary>
        public static string DisplayName102 {
            get {
                return ResourceManager.GetString("DisplayName102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 只获取未读邮件 的本地化字符串。
        /// </summary>
        public static string DisplayName103 {
            get {
                return ResourceManager.GetString("DisplayName103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记为已读 的本地化字符串。
        /// </summary>
        public static string DisplayName104 {
            get {
                return ResourceManager.GetString("DisplayName104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 回复所有人 的本地化字符串。
        /// </summary>
        public static string DisplayName105 {
            get {
                return ResourceManager.GetString("DisplayName105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存路径 的本地化字符串。
        /// </summary>
        public static string DisplayName106 {
            get {
                return ResourceManager.GetString("DisplayName106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密送 的本地化字符串。
        /// </summary>
        public static string DisplayName107 {
            get {
                return ResourceManager.GetString("DisplayName107", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 显示名 的本地化字符串。
        /// </summary>
        public static string DisplayName108 {
            get {
                return ResourceManager.GetString("DisplayName108", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否保存成草稿 的本地化字符串。
        /// </summary>
        public static string DisplayName109 {
            get {
                return ResourceManager.GetString("DisplayName109", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 事务 的本地化字符串。
        /// </summary>
        public static string DisplayName11 {
            get {
                return ResourceManager.GetString("DisplayName11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 游标移动距离 的本地化字符串。
        /// </summary>
        public static string DisplayName110 {
            get {
                return ResourceManager.GetString("DisplayName110", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否选中 的本地化字符串。
        /// </summary>
        public static string DisplayName111 {
            get {
                return ResourceManager.GetString("DisplayName111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左 的本地化字符串。
        /// </summary>
        public static string DisplayName112 {
            get {
                return ResourceManager.GetString("DisplayName112", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右 的本地化字符串。
        /// </summary>
        public static string DisplayName113 {
            get {
                return ResourceManager.GetString("DisplayName113", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上 的本地化字符串。
        /// </summary>
        public static string DisplayName114 {
            get {
                return ResourceManager.GetString("DisplayName114", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下 的本地化字符串。
        /// </summary>
        public static string DisplayName115 {
            get {
                return ResourceManager.GetString("DisplayName115", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开头 的本地化字符串。
        /// </summary>
        public static string DisplayName116 {
            get {
                return ResourceManager.GetString("DisplayName116", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结尾 的本地化字符串。
        /// </summary>
        public static string DisplayName117 {
            get {
                return ResourceManager.GetString("DisplayName117", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下一页 的本地化字符串。
        /// </summary>
        public static string DisplayName118 {
            get {
                return ResourceManager.GetString("DisplayName118", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体大小 的本地化字符串。
        /// </summary>
        public static string DisplayName119 {
            get {
                return ResourceManager.GetString("DisplayName119", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件路径 的本地化字符串。
        /// </summary>
        public static string DisplayName12 {
            get {
                return ResourceManager.GetString("DisplayName12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体颜色 的本地化字符串。
        /// </summary>
        public static string DisplayName120 {
            get {
                return ResourceManager.GetString("DisplayName120", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下划线 的本地化字符串。
        /// </summary>
        public static string DisplayName121 {
            get {
                return ResourceManager.GetString("DisplayName121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体阴影 的本地化字符串。
        /// </summary>
        public static string DisplayName122 {
            get {
                return ResourceManager.GetString("DisplayName122", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左边距 的本地化字符串。
        /// </summary>
        public static string DisplayName123 {
            get {
                return ResourceManager.GetString("DisplayName123", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 右边距 的本地化字符串。
        /// </summary>
        public static string DisplayName124 {
            get {
                return ResourceManager.GetString("DisplayName124", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 上边距 的本地化字符串。
        /// </summary>
        public static string DisplayName125 {
            get {
                return ResourceManager.GetString("DisplayName125", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 下边距 的本地化字符串。
        /// </summary>
        public static string DisplayName126 {
            get {
                return ResourceManager.GetString("DisplayName126", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 退格次数 的本地化字符串。
        /// </summary>
        public static string DisplayName127 {
            get {
                return ResourceManager.GetString("DisplayName127", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 复制 的本地化字符串。
        /// </summary>
        public static string DisplayName128 {
            get {
                return ResourceManager.GetString("DisplayName128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粘贴 的本地化字符串。
        /// </summary>
        public static string DisplayName129 {
            get {
                return ResourceManager.GetString("DisplayName129", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分隔符 的本地化字符串。
        /// </summary>
        public static string DisplayName13 {
            get {
                return ResourceManager.GetString("DisplayName13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文档内容 的本地化字符串。
        /// </summary>
        public static string DisplayName130 {
            get {
                return ResourceManager.GetString("DisplayName130", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片链接 的本地化字符串。
        /// </summary>
        public static string DisplayName131 {
            get {
                return ResourceManager.GetString("DisplayName131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 书签名称 的本地化字符串。
        /// </summary>
        public static string DisplayName132 {
            get {
                return ResourceManager.GetString("DisplayName132", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超链接名称 的本地化字符串。
        /// </summary>
        public static string DisplayName133 {
            get {
                return ResourceManager.GetString("DisplayName133", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超链接标签 的本地化字符串。
        /// </summary>
        public static string DisplayName134 {
            get {
                return ResourceManager.GetString("DisplayName134", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超链接地址 的本地化字符串。
        /// </summary>
        public static string DisplayName135 {
            get {
                return ResourceManager.GetString("DisplayName135", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分页/换行次数 的本地化字符串。
        /// </summary>
        public static string DisplayName136 {
            get {
                return ResourceManager.GetString("DisplayName136", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分页 的本地化字符串。
        /// </summary>
        public static string DisplayName137 {
            get {
                return ResourceManager.GetString("DisplayName137", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 换行 的本地化字符串。
        /// </summary>
        public static string DisplayName138 {
            get {
                return ResourceManager.GetString("DisplayName138", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文本内容 的本地化字符串。
        /// </summary>
        public static string DisplayName139 {
            get {
                return ResourceManager.GetString("DisplayName139", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字符编码 的本地化字符串。
        /// </summary>
        public static string DisplayName14 {
            get {
                return ResourceManager.GetString("DisplayName14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格名称 的本地化字符串。
        /// </summary>
        public static string DisplayName141 {
            get {
                return ResourceManager.GetString("DisplayName141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 合并/拆分 的本地化字符串。
        /// </summary>
        public static string DisplayName142 {
            get {
                return ResourceManager.GetString("DisplayName142", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标文件路径 的本地化字符串。
        /// </summary>
        public static string DisplayName143 {
            get {
                return ResourceManager.GetString("DisplayName143", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标单元格行 的本地化字符串。
        /// </summary>
        public static string DisplayName144 {
            get {
                return ResourceManager.GetString("DisplayName144", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标单元格列 的本地化字符串。
        /// </summary>
        public static string DisplayName145 {
            get {
                return ResourceManager.GetString("DisplayName145", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标单元格名称 的本地化字符串。
        /// </summary>
        public static string DisplayName146 {
            get {
                return ResourceManager.GetString("DisplayName146", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标工作表 的本地化字符串。
        /// </summary>
        public static string DisplayName147 {
            get {
                return ResourceManager.GetString("DisplayName147", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始单元格行 的本地化字符串。
        /// </summary>
        public static string DisplayName148 {
            get {
                return ResourceManager.GetString("DisplayName148", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始单元格列 的本地化字符串。
        /// </summary>
        public static string DisplayName149 {
            get {
                return ResourceManager.GetString("DisplayName149", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列名 的本地化字符串。
        /// </summary>
        public static string DisplayName15 {
            get {
                return ResourceManager.GetString("DisplayName15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始单元格名称 的本地化字符串。
        /// </summary>
        public static string DisplayName150 {
            get {
                return ResourceManager.GetString("DisplayName150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终点单元格行 的本地化字符串。
        /// </summary>
        public static string DisplayName151 {
            get {
                return ResourceManager.GetString("DisplayName151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终点单元格列 的本地化字符串。
        /// </summary>
        public static string DisplayName152 {
            get {
                return ResourceManager.GetString("DisplayName152", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 终点单元格名称 的本地化字符串。
        /// </summary>
        public static string DisplayName153 {
            get {
                return ResourceManager.GetString("DisplayName153", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表头 的本地化字符串。
        /// </summary>
        public static string DisplayName154 {
            get {
                return ResourceManager.GetString("DisplayName154", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有工作表 的本地化字符串。
        /// </summary>
        public static string DisplayName155 {
            get {
                return ResourceManager.GetString("DisplayName155", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 所有区域 的本地化字符串。
        /// </summary>
        public static string DisplayName156 {
            get {
                return ResourceManager.GetString("DisplayName156", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格起始行 的本地化字符串。
        /// </summary>
        public static string DisplayName157 {
            get {
                return ResourceManager.GetString("DisplayName157", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格起始列 的本地化字符串。
        /// </summary>
        public static string DisplayName158 {
            get {
                return ResourceManager.GetString("DisplayName158", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格起始名称 的本地化字符串。
        /// </summary>
        public static string DisplayName159 {
            get {
                return ResourceManager.GetString("DisplayName159", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行 的本地化字符串。
        /// </summary>
        public static string DisplayName16 {
            get {
                return ResourceManager.GetString("DisplayName16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格终点行 的本地化字符串。
        /// </summary>
        public static string DisplayName160 {
            get {
                return ResourceManager.GetString("DisplayName160", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格终点列 的本地化字符串。
        /// </summary>
        public static string DisplayName161 {
            get {
                return ResourceManager.GetString("DisplayName161", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格终点名称 的本地化字符串。
        /// </summary>
        public static string DisplayName162 {
            get {
                return ResourceManager.GetString("DisplayName162", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 查找内容 的本地化字符串。
        /// </summary>
        public static string DisplayName163 {
            get {
                return ResourceManager.GetString("DisplayName163", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 替换内容 的本地化字符串。
        /// </summary>
        public static string DisplayName164 {
            get {
                return ResourceManager.GetString("DisplayName164", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区分大小写 的本地化字符串。
        /// </summary>
        public static string DisplayName165 {
            get {
                return ResourceManager.GetString("DisplayName165", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格匹配 的本地化字符串。
        /// </summary>
        public static string DisplayName166 {
            get {
                return ResourceManager.GetString("DisplayName166", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 区分半全角 的本地化字符串。
        /// </summary>
        public static string DisplayName167 {
            get {
                return ResourceManager.GetString("DisplayName167", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 有效数据 的本地化字符串。
        /// </summary>
        public static string DisplayName168 {
            get {
                return ResourceManager.GetString("DisplayName168", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 活动区域 的本地化字符串。
        /// </summary>
        public static string DisplayName169 {
            get {
                return ResourceManager.GetString("DisplayName169", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列 的本地化字符串。
        /// </summary>
        public static string DisplayName17 {
            get {
                return ResourceManager.GetString("DisplayName17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A1单元格列/行截止 的本地化字符串。
        /// </summary>
        public static string DisplayName170 {
            get {
                return ResourceManager.GetString("DisplayName170", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行数 的本地化字符串。
        /// </summary>
        public static string DisplayName171 {
            get {
                return ResourceManager.GetString("DisplayName171", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列数 的本地化字符串。
        /// </summary>
        public static string DisplayName172 {
            get {
                return ResourceManager.GetString("DisplayName172", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行号/列号 的本地化字符串。
        /// </summary>
        public static string DisplayName173 {
            get {
                return ResourceManager.GetString("DisplayName173", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行/列 的本地化字符串。
        /// </summary>
        public static string DisplayName174 {
            get {
                return ResourceManager.GetString("DisplayName174", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行/列数据 的本地化字符串。
        /// </summary>
        public static string DisplayName175 {
            get {
                return ResourceManager.GetString("DisplayName175", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作表名称列表 的本地化字符串。
        /// </summary>
        public static string DisplayName176 {
            get {
                return ResourceManager.GetString("DisplayName176", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格数据 的本地化字符串。
        /// </summary>
        public static string DisplayName177 {
            get {
                return ResourceManager.GetString("DisplayName177", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作表名称 的本地化字符串。
        /// </summary>
        public static string DisplayName18 {
            get {
                return ResourceManager.GetString("DisplayName18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格内容 的本地化字符串。
        /// </summary>
        public static string DisplayName19 {
            get {
                return ResourceManager.GetString("DisplayName19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序名称 的本地化字符串。
        /// </summary>
        public static string DisplayName2 {
            get {
                return ResourceManager.GetString("DisplayName2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否创建新文档 的本地化字符串。
        /// </summary>
        public static string DisplayName20 {
            get {
                return ResourceManager.GetString("DisplayName20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 流程是否可见 的本地化字符串。
        /// </summary>
        public static string DisplayName21 {
            get {
                return ResourceManager.GetString("DisplayName21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 程序是否退出 的本地化字符串。
        /// </summary>
        public static string DisplayName22 {
            get {
                return ResourceManager.GetString("DisplayName22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 保存 的本地化字符串。
        /// </summary>
        public static string DisplayName23 {
            get {
                return ResourceManager.GetString("DisplayName23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 另存为 的本地化字符串。
        /// </summary>
        public static string DisplayName24 {
            get {
                return ResourceManager.GetString("DisplayName24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行列操作 的本地化字符串。
        /// </summary>
        public static string DisplayName25 {
            get {
                return ResourceManager.GetString("DisplayName25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行列选择 的本地化字符串。
        /// </summary>
        public static string DisplayName26 {
            get {
                return ResourceManager.GetString("DisplayName26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行号/列号(开始) 的本地化字符串。
        /// </summary>
        public static string DisplayName27 {
            get {
                return ResourceManager.GetString("DisplayName27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行号/列号(结束) 的本地化字符串。
        /// </summary>
        public static string DisplayName28 {
            get {
                return ResourceManager.GetString("DisplayName28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 单元格填充色 的本地化字符串。
        /// </summary>
        public static string DisplayName29 {
            get {
                return ResourceManager.GetString("DisplayName29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用于保存数据库连接的变量(仅支持DatabaseConnection) 的本地化字符串。
        /// </summary>
        public static string DisplayName3 {
            get {
                return ResourceManager.GetString("DisplayName3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对齐方式 的本地化字符串。
        /// </summary>
        public static string DisplayName30 {
            get {
                return ResourceManager.GetString("DisplayName30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字体 的本地化字符串。
        /// </summary>
        public static string DisplayName31 {
            get {
                return ResourceManager.GetString("DisplayName31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 字号 的本地化字符串。
        /// </summary>
        public static string DisplayName32 {
            get {
                return ResourceManager.GetString("DisplayName32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 颜色 的本地化字符串。
        /// </summary>
        public static string DisplayName33 {
            get {
                return ResourceManager.GetString("DisplayName33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 粗体 的本地化字符串。
        /// </summary>
        public static string DisplayName34 {
            get {
                return ResourceManager.GetString("DisplayName34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 斜体 的本地化字符串。
        /// </summary>
        public static string DisplayName35 {
            get {
                return ResourceManager.GetString("DisplayName35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 底线 的本地化字符串。
        /// </summary>
        public static string DisplayName36 {
            get {
                return ResourceManager.GetString("DisplayName36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 行高 的本地化字符串。
        /// </summary>
        public static string DisplayName37 {
            get {
                return ResourceManager.GetString("DisplayName37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 列宽 的本地化字符串。
        /// </summary>
        public static string DisplayName38 {
            get {
                return ResourceManager.GetString("DisplayName38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 边框选择 的本地化字符串。
        /// </summary>
        public static string DisplayName39 {
            get {
                return ResourceManager.GetString("DisplayName39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时时间 的本地化字符串。
        /// </summary>
        public static string DisplayName4 {
            get {
                return ResourceManager.GetString("DisplayName4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作表次序 的本地化字符串。
        /// </summary>
        public static string DisplayName40 {
            get {
                return ResourceManager.GetString("DisplayName40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 功能选项 的本地化字符串。
        /// </summary>
        public static string DisplayName41 {
            get {
                return ResourceManager.GetString("DisplayName41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 工作表新名称 的本地化字符串。
        /// </summary>
        public static string DisplayName42 {
            get {
                return ResourceManager.GetString("DisplayName42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 VBA名称 的本地化字符串。
        /// </summary>
        public static string DisplayName43 {
            get {
                return ResourceManager.GetString("DisplayName43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 返回值 的本地化字符串。
        /// </summary>
        public static string DisplayName44 {
            get {
                return ResourceManager.GetString("DisplayName44", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 路径 的本地化字符串。
        /// </summary>
        public static string DisplayName45 {
            get {
                return ResourceManager.GetString("DisplayName45", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否存在 的本地化字符串。
        /// </summary>
        public static string DisplayName46 {
            get {
                return ResourceManager.GetString("DisplayName46", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 本地路径 的本地化字符串。
        /// </summary>
        public static string DisplayName47 {
            get {
                return ResourceManager.GetString("DisplayName47", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建文件夹 的本地化字符串。
        /// </summary>
        public static string DisplayName48 {
            get {
                return ResourceManager.GetString("DisplayName48", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 包含子文件夹 的本地化字符串。
        /// </summary>
        public static string DisplayName49 {
            get {
                return ResourceManager.GetString("DisplayName49", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误继续执行 的本地化字符串。
        /// </summary>
        public static string DisplayName5 {
            get {
                return ResourceManager.GetString("DisplayName5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 覆盖 的本地化字符串。
        /// </summary>
        public static string DisplayName50 {
            get {
                return ResourceManager.GetString("DisplayName50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 枚举文件 的本地化字符串。
        /// </summary>
        public static string DisplayName51 {
            get {
                return ResourceManager.GetString("DisplayName51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTP路径 的本地化字符串。
        /// </summary>
        public static string DisplayName52 {
            get {
                return ResourceManager.GetString("DisplayName52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建 的本地化字符串。
        /// </summary>
        public static string DisplayName53 {
            get {
                return ResourceManager.GetString("DisplayName53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主机 的本地化字符串。
        /// </summary>
        public static string DisplayName54 {
            get {
                return ResourceManager.GetString("DisplayName54", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 端口 的本地化字符串。
        /// </summary>
        public static string DisplayName55 {
            get {
                return ResourceManager.GetString("DisplayName55", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户名 的本地化字符串。
        /// </summary>
        public static string DisplayName56 {
            get {
                return ResourceManager.GetString("DisplayName56", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码 的本地化字符串。
        /// </summary>
        public static string DisplayName57 {
            get {
                return ResourceManager.GetString("DisplayName57", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 匿名登录 的本地化字符串。
        /// </summary>
        public static string DisplayName58 {
            get {
                return ResourceManager.GetString("DisplayName58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FTPS模式 的本地化字符串。
        /// </summary>
        public static string DisplayName59 {
            get {
                return ResourceManager.GetString("DisplayName59", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 现有数据库连接 的本地化字符串。
        /// </summary>
        public static string DisplayName6 {
            get {
                return ResourceManager.GetString("DisplayName6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 使用SFTP 的本地化字符串。
        /// </summary>
        public static string DisplayName60 {
            get {
                return ResourceManager.GetString("DisplayName60", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端证书路径 的本地化字符串。
        /// </summary>
        public static string DisplayName61 {
            get {
                return ResourceManager.GetString("DisplayName61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 客户端证书密码 的本地化字符串。
        /// </summary>
        public static string DisplayName62 {
            get {
                return ResourceManager.GetString("DisplayName62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 接受所有证书 的本地化字符串。
        /// </summary>
        public static string DisplayName63 {
            get {
                return ResourceManager.GetString("DisplayName63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件账户 的本地化字符串。
        /// </summary>
        public static string DisplayName64 {
            get {
                return ResourceManager.GetString("DisplayName64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件夹 的本地化字符串。
        /// </summary>
        public static string DisplayName65 {
            get {
                return ResourceManager.GetString("DisplayName65", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 安全连接 的本地化字符串。
        /// </summary>
        public static string DisplayName66 {
            get {
                return ResourceManager.GetString("DisplayName66", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索消息数 的本地化字符串。
        /// </summary>
        public static string DisplayName67 {
            get {
                return ResourceManager.GetString("DisplayName67", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标记消息删除 的本地化字符串。
        /// </summary>
        public static string DisplayName68 {
            get {
                return ResourceManager.GetString("DisplayName68", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 标为已读 的本地化字符串。
        /// </summary>
        public static string DisplayName69 {
            get {
                return ResourceManager.GetString("DisplayName69", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 表名 的本地化字符串。
        /// </summary>
        public static string DisplayName7 {
            get {
                return ResourceManager.GetString("DisplayName7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 仅检索未读消息 的本地化字符串。
        /// </summary>
        public static string DisplayName70 {
            get {
                return ResourceManager.GetString("DisplayName70", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 检索所有未读消息 的本地化字符串。
        /// </summary>
        public static string DisplayName71 {
            get {
                return ResourceManager.GetString("DisplayName71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题关键字 的本地化字符串。
        /// </summary>
        public static string DisplayName72 {
            get {
                return ResourceManager.GetString("DisplayName72", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发件人关键字 的本地化字符串。
        /// </summary>
        public static string DisplayName73 {
            get {
                return ResourceManager.GetString("DisplayName73", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 内容关键字 的本地化字符串。
        /// </summary>
        public static string DisplayName74 {
            get {
                return ResourceManager.GetString("DisplayName74", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息 的本地化字符串。
        /// </summary>
        public static string DisplayName75 {
            get {
                return ResourceManager.GetString("DisplayName75", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件 的本地化字符串。
        /// </summary>
        public static string DisplayName76 {
            get {
                return ResourceManager.GetString("DisplayName76", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片路径列表 的本地化字符串。
        /// </summary>
        public static string DisplayName77 {
            get {
                return ResourceManager.GetString("DisplayName77", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 图片资源列表 的本地化字符串。
        /// </summary>
        public static string DisplayName78 {
            get {
                return ResourceManager.GetString("DisplayName78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目标文件夹 的本地化字符串。
        /// </summary>
        public static string DisplayName79 {
            get {
                return ResourceManager.GetString("DisplayName79", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 执行结果 的本地化字符串。
        /// </summary>
        public static string DisplayName8 {
            get {
                return ResourceManager.GetString("DisplayName8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 源文件夹 的本地化字符串。
        /// </summary>
        public static string DisplayName80 {
            get {
                return ResourceManager.GetString("DisplayName80", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件消息 的本地化字符串。
        /// </summary>
        public static string DisplayName81 {
            get {
                return ResourceManager.GetString("DisplayName81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 附件列表 的本地化字符串。
        /// </summary>
        public static string DisplayName82 {
            get {
                return ResourceManager.GetString("DisplayName82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 名称 的本地化字符串。
        /// </summary>
        public static string DisplayName83 {
            get {
                return ResourceManager.GetString("DisplayName83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发件人 的本地化字符串。
        /// </summary>
        public static string DisplayName84 {
            get {
                return ResourceManager.GetString("DisplayName84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 抄送 的本地化字符串。
        /// </summary>
        public static string DisplayName85 {
            get {
                return ResourceManager.GetString("DisplayName85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密件抄送 的本地化字符串。
        /// </summary>
        public static string DisplayName86 {
            get {
                return ResourceManager.GetString("DisplayName86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 主题 的本地化字符串。
        /// </summary>
        public static string DisplayName87 {
            get {
                return ResourceManager.GetString("DisplayName87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正文 的本地化字符串。
        /// </summary>
        public static string DisplayName88 {
            get {
                return ResourceManager.GetString("DisplayName88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 优先级 的本地化字符串。
        /// </summary>
        public static string DisplayName89 {
            get {
                return ResourceManager.GetString("DisplayName89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 命令类型 的本地化字符串。
        /// </summary>
        public static string DisplayName9 {
            get {
                return ResourceManager.GetString("DisplayName9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 HTML格式 的本地化字符串。
        /// </summary>
        public static string DisplayName90 {
            get {
                return ResourceManager.GetString("DisplayName90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件 的本地化字符串。
        /// </summary>
        public static string DisplayName91 {
            get {
                return ResourceManager.GetString("DisplayName91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 消息体 的本地化字符串。
        /// </summary>
        public static string DisplayName92 {
            get {
                return ResourceManager.GetString("DisplayName92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 存档路径(.pst) 的本地化字符串。
        /// </summary>
        public static string DisplayName93 {
            get {
                return ResourceManager.GetString("DisplayName93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 待存档账户 的本地化字符串。
        /// </summary>
        public static string DisplayName94 {
            get {
                return ResourceManager.GetString("DisplayName94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件对象 的本地化字符串。
        /// </summary>
        public static string DisplayName95 {
            get {
                return ResourceManager.GetString("DisplayName95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 超时时间(毫秒) 的本地化字符串。
        /// </summary>
        public static string DisplayName96 {
            get {
                return ResourceManager.GetString("DisplayName96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取邮件个数 的本地化字符串。
        /// </summary>
        public static string DisplayName97 {
            get {
                return ResourceManager.GetString("DisplayName97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输出邮件列表 的本地化字符串。
        /// </summary>
        public static string DisplayName98 {
            get {
                return ResourceManager.GetString("DisplayName98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件目录 的本地化字符串。
        /// </summary>
        public static string DisplayName99 {
            get {
                return ResourceManager.GetString("DisplayName99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SQL编辑 的本地化字符串。
        /// </summary>
        public static string EditSQL {
            get {
                return ResourceManager.GetString("EditSQL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束区域 的本地化字符串。
        /// </summary>
        public static string EndArea {
            get {
                return ResourceManager.GetString("EndArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 打开文件路径 的本地化字符串。
        /// </summary>
        public static string FilePathToOpen {
            get {
                return ResourceManager.GetString("FilePathToOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 文件保存路径 的本地化字符串。
        /// </summary>
        public static string FilePathToSave {
            get {
                return ResourceManager.GetString("FilePathToSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 隐藏 的本地化字符串。
        /// </summary>
        public static string HideText {
            get {
                return ResourceManager.GetString("HideText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件文件夹 的本地化字符串。
        /// </summary>
        public static string MailFolder {
            get {
                return ResourceManager.GetString("MailFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 邮件消息 的本地化字符串。
        /// </summary>
        public static string MailMessage {
            get {
                return ResourceManager.GetString("MailMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 新建数据库连接 的本地化字符串。
        /// </summary>
        public static string NewDatabaseConnection {
            get {
                return ResourceManager.GetString("NewDatabaseConnection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数 的本地化字符串。
        /// </summary>
        public static string ParameterText {
            get {
                return ResourceManager.GetString("ParameterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 开始区域 的本地化字符串。
        /// </summary>
        public static string StartArea {
            get {
                return ResourceManager.GetString("StartArea", resourceCulture);
            }
        }
    }
}
